services:
  - type: web
    name: openrank-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URLS
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        sync: false
      - key: GITHUB_API_TOKEN
        sync: false
